#!/bin/bash

curl -fsSL https://raw.githubusercontent.com/mattkellymt/techstack/refs/heads/main/setup | sh

if [ ! -d ~/github.com/mattkellymt/techstack ]; then
	mkdir -p ~/github.com/mattkellymt
	cd ~/github.com/mattkellymt
	git clone https://github.com/mattkellymt/techstack.git
fi
 
