#!/bin/bash

sudo dnf upgrade -y 
sudo dnf install -y git

mkdir -p ~/github.com/mattkellymt
cd ~/github.com/mattkellymt

if [ ! -d techstack ]; then
	git clone https://github.com/mattkellymt/techstack.git
fi

cd techstack
sh setup
