#!/bin/bash
set -eo pipefail

script_dir=$(cd -- "$(dirname -- "${0}")" && pwd)
image_name="sandbox"
build_root=$(sudo mktemp -d --tmpdir=/dev/shm "${image_name}.XXXXXXXX")
image_root="${build_root}/bundle/rootfs"

cleanup() {
	sudo rm -rf -- "${build_root}"
}
trap cleanup EXIT

packages=(
	bash
	coreutils
	dnf
	fedora-release
	shadow-utils
	sudo
	systemd
	systemd-networkd
	util-linux
)

sudo skopeo copy \
	docker://registry.fedoraproject.org/fedora:44 \
	"oci:${build_root}/image:44"
sudo umoci unpack \
	--image "${build_root}/image:44" \
	"${build_root}/bundle"

sudo cp -R "${script_dir}/machine/." "${image_root}/"
sudo chroot "${image_root}" dnf -y install "${packages[@]}"
sudo chroot "${image_root}" systemctl enable systemd-networkd.service

sudo chroot "${image_root}" rm -f /etc/machine-id
sudo chroot "${image_root}" systemd-machine-id-setup

sudo chroot "${image_root}" chmod 440 /etc/sudoers.d/agent
sudo chroot "${image_root}" useradd --create-home --user-group --groups wheel agent
sudo chroot "${image_root}" passwd --delete agent

sudo systemctl stop "systemd-nspawn@${image_name}.service" 2>/dev/null || true
sudo machinectl remove "${image_name}" 2>/dev/null || true

sudo cp -R "${script_dir}/host/." /
sudo mv "${image_root}" "/var/lib/machines/${image_name}"
sudo systemctl enable --now "systemd-nspawn@${image_name}.service"
