#!/bin/bash

# fedora 44
sudo dnf upgrade -y --refresh
sudo dnf group install -y development-tools
sudo dnf install -y \
	vim pass git jq yq bubblewrap gawk dnf5-plugins zstd

# uv
if ! command -v uv &> /dev/null; then
	curl -LsSf https://astral.sh/uv/install.sh | sh
fi

if [ -f pyproject.toml ]; then
	uv sync
fi

# gh
mkdir -p ~/github.com

if ! command -v gh &> /dev/null; then
	url="https://cli.github.com/packages/rpm/gh-cli.repo"
	sudo dnf config-manager addrepo --from-repofile="$url"
	sudo dnf install -y gh
fi

# ollama
if ! command -v ollama &> /dev/null; then
        curl -fsSL https://ollama.com/install.sh | sh
fi

# opencode
if ! command -v opencode &> /dev/null; then
	curl -fsSL https://opencode.ai/install | bash
	source ~/.bashrc
fi
