#!/bin/bash
set -euo pipefail 

# fedora 44
sudo dnf upgrade -y
sudo dnf group install -y development-tools
sudo dnf install -y \
	vim pass git jq yq bubblewrap gawk dnf5-plugins zstd

# cloning
mkdir -p ~/github.com/mattkellymt
cd ~/github.com/mattkellymt

if [ ! -d techstack ]; then
	git clone https://github.com/mattkellymt/techstack.git
fi

cd techstack
chmod +x setup
chmod +x upgrade

# uv
if ! command -v uv &> /dev/null; then
	curl -LsSf https://astral.sh/uv/install.sh | sh
fi

cd ~/github.com/mattkellymt/techstack
uv sync

# gh
if ! command -v gh &> /dev/null; then
	url="https://cli.github.com/packages/rpm/gh-cli.repo"
	sudo dnf config-manager addrepo --from-repofile="$url"
	sudo dnf install -y gh
fi

# ollama
if ! command -v ollama &> /dev/null; then
	curl -fsSL https://ollama.com/install.sh | sh
fi

# opencode
if ! command -v opencode &> /dev/null; then
	curl -fsSL https://opencode.ai/install | sh
fi

# linking
mkdir -p ~/.local/bin
ln -sf ~/github.com/mattkellymt/techstack/setup ~/.local/bin/setup
ln -sf ~/github.com/mattkellymt/techstack/upgrade ~/.local/bin/upgrade
ln -sf ~/.opencode/bin/opencode ~/.local/bin/opencode
