#!/bin/bash
set -euo pipefail 

# fedora 44
sudo dnf upgrade -y

# uv
uv self update
uv tool upgrade --all

if [ -f ~/github.com/mattkellymt/techstack/pyproject.toml ]; then
	cd ~/github.com/mattkellymt/techstack
	uv sync --upgrade
fi

# ollama
url="https://api.github.com/repos/ollama/ollama/releases/latest"
latest=$(curl -fsSL "$url" | jq -r .tag_name | sed 's/v//')
current=$(ollama --version | sed 's/ollama version is //')

if [ "$latest" != "$current" ]; then
	curl -fsSL https://ollama.com/install.sh | sh
fi

# opencode
opencode upgrade
