[Config]
MinimumVersion=26

[Distribution]
Distribution=fedora
Release=44

[Output]
Format=directory
OutputDirectory=/var/lib/machines
Output=sandbox

[Content]
Packages=
	fedora-release
	bash
	coreutils
	dnf
	shadow-utils
	sudo
	util-linux
	systemd
	systemd-networkd
WithRecommends=yes
RootPassword=hashed:
MachineId=random
Bootable=no

[Runtime]
Machine=sandbox
