#!/bin/bash
set -euo pipefail

main() {
	# dnf
	sudo dnf upgrade -y --refresh

	# systemd-nspawn container tooling
	sudo dnf install -y systemd-container systemd-resolved

	# ensure container networking + DNS are enabled and running (idempotent)
	sudo systemctl enable --now systemd-networkd
	sudo systemctl enable --now systemd-resolved
}
main
