#!/bin/bash
set -eo pipefail

if ! command -v brew >/dev/null 2>&1; then
	curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
fi

if ! grep -Fqx 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' "${HOME}/.bashrc"; then
	echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> "${HOME}/.bashrc"
fi

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
