#!/bin/bash
set -eo pipefail 

script_dir="$HOME/github.com/mattkellymt/techstack/ubuntu"

# apt
sudo apt update -y
sudo apt upgrade -y

sudo apt install -y \
	vim git curl htop pass \
	bubblewrap gawk zstd cmake build-essential

# github
mkdir -p "$HOME/github.com/mattkellymt"
cd "$HOME/github.com/mattkellymt"

if [ ! -d techstack ]; then
	git clone https://github.com/mattkellymt/techstack.git
fi

cd "$HOME/github.com/mattkellymt/techstack/fedora"
git fetch origin main
current_branch=$(git branch --show-current)

if [ "$current_branch" = "main" ]; then
	git reset --hard origin/main
	git clean -fd
fi

mkdir -p "$HOME/.local/bin"
ln -sf "$HOME/github.com/mattkellymt/techstack/fedora/stack" "$HOME/.local/bin/stack"

# brew
$script_dir/install_brew
brew install -y jq yq uv

# agents
$script_dir/install_agents
