#!/bin/bash
set -eo pipefail

script_dir=$(cd -- "$(dirname -- "${0}")" && pwd)

# apt
sudo apt-get update
sudo env DEBIAN_FRONTEND=noninteractive apt-get -y upgrade
sudo env DEBIAN_FRONTEND=noninteractive apt-get -y install \
	debootstrap \
	systemd-container

# bridge
"${script_dir}/install_bridge"

# image
"${script_dir}/build_image"
