#!/bin/bash
set -eo pipefail 

main() {
	# apt
	sudo apt update -y
	sudo apt upgrade -y
	
	sudo apt install -y build-essential
	sudo apt install -y \
		vim neovim python3-neovim git \
		bubblewrap gawk zstd cmake
	
	# brew
	if ! command -v brew &> /dev/null; then
		curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
		echo >> ~/.bashrc
		echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv bash)"' >> ~/.bashrc
		eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv bash)"
		source ~/.bashrc
	fi
	
	brew install -y jq yq hf htop pass curl

	# github
	mkdir -p ~/github.com/mattkellymt
	cd ~/github.com/mattkellymt
	
	if [ ! -d techstack ]; then
		git clone https://github.com/mattkellymt/techstack.git
	fi
	
	cd ~/github.com/mattkellymt/techstack/ubuntu
	git fetch origin main
	current_branch=$(git branch --show-current)
	
	if [ "$current_branch" = "main" ]; then
	    git reset --hard origin/main
	    git clean -fd
	fi

	mkdir -p ~/.local/bin
	ln -sf ~/github.com/mattkellymt/techstack/ubuntu/stack ~/.local/bin/stack

	# uv
	if ! command -v uv &> /dev/null; then
		brew install -y uv
	fi
	
	cd ~/github.com/mattkellymt/techstack
	uv sync
	
	# opencode
	if ! command -v opencode &> /dev/null; then
		brew tap anomalyco/tap
		brew trust anomalyco/tap
		brew install -y anomalyco/tap/opencode
	fi
	
	# codex
	if ! command -v codex &> /dev/null; then
		brew install -y --cask codex
	fi
	
	# claude
	if ! command -v claude &> /dev/null; then
		brew install -y --cask claude-code
	fi
	
	# google antigravity
	if ! command -v agy &> /dev/null; then
		brew install -y --cask antigravity-cli
	fi
	
	# grok
	if ! command -v grok &> /dev/null; then
		curl -fsSL https://x.ai/cli/install.sh | bash
		source ~/.bashrc
	fi
	
	# ollama
	if ! command -v ollama &> /dev/null; then
		curl -fsSL https://ollama.com/install.sh | bash
		source ~/.bashrc
	fi 
	
	# unsloth
	if ! command -v unsloth &> /dev/null; then
		curl -fsSL https://unsloth.ai/install.sh | UNSLOTH_SKIP_AUTOSTART=1 bash
		source ~/.bashrc
	fi 
}
main
