#!/bin/bash
set -eo pipefail 
main() {
    # ubuntu 24.04
    sudo apt update -y
    sudo apt upgrade -y
    
    # github
    cd ~/github.com/mattkellymt/techstack
    git fetch origin main
    current_branch=$(git branch --show-current)
    
    if [ "$current_branch" = "main" ]; then
        git reset --hard origin/main
        git clean -fd
    fi
    
    # brew
    brew update
    brew upgrade -y
    
    # uv
    cd ~/github.com/mattkellymt/techstack
    uv tool upgrade --all
    uv sync --upgrade
    
    # ollama
    curl -fsSL https://ollama.com/install.sh | sh
    
    # unsloth
    curl -fsSL https://unsloth.ai/install.sh | UNSLOTH_SKIP_AUTOSTART=1 bash
}
main

