#!/bin/bash
set -eo pipefail 

# apt
sudo apt update -y
sudo apt upgrade -y

# brew
brew update
brew upgrade -y

# github
cd ~/github.com/mattkellymt/techstack
git fetch origin main
current_branch=$(git branch --show-current)

if [ "$current_branch" = "main" ]; then
    git reset --hard origin/main
    git clean -fd
fi

# grok
curl -fsSL https://x.ai/cli/install.sh | bash
source ~/.bashrc
