#!/bin/zsh
set -eo pipefail

# opencode
if ! command -v opencode >/dev/null 2>&1; then
	brew tap anomalyco/tap
	brew trust anomalyco/tap
	brew install anomalyco/tap/opencode
fi

# codex
if ! command -v codex >/dev/null 2>&1; then
	brew install --cask codex
fi

# claude
if ! command -v claude >/dev/null 2>&1; then
	brew install --cask claude-code
fi

# google antigravity
if ! command -v agy >/dev/null 2>&1; then
	brew install --cask antigravity-cli
fi

# grok
if ! command -v grok >/dev/null 2>&1; then
	curl -fsSL https://x.ai/cli/install.sh | zsh
fi
