[Distribution]
Distribution=fedora
Release=44

[Output]
Format=directory
OutputDirectory=/var/lib/machines
Output=agent

[Content]
Packages=
	fedora-release
	sudo
	bash
	dnf
	systemd
	systemd-networkd
	systemd-resolved
	mkosi
WithRecommends=yes
RootPassword=hashed:
MachineId=random
Bootable=no
