#!/bin/bash
set -eo pipefail

script_dir=$(cd -- "$(dirname -- "${0}")" && pwd)
image_name="sandbox"
build_root=$(sudo mktemp -d --tmpdir=/dev/shm "${image_name}.XXXXXXXX")
image_root="${build_root}/bundle/rootfs"

build_cleanup() {
	sudo rm -rf -- "${build_root}"
}

trap build_cleanup EXIT

packages=(
	bash
	coreutils
	dnf
	fedora-release
	shadow-utils
	sudo
	systemd
	systemd-networkd
	util-linux
)

sudo skopeo copy \
	docker://docker.io/fedora:44 \
	"oci:${build_root}/image:44"
sudo umoci unpack \
	--image "${build_root}/image:44" \
	"${build_root}/bundle"

sudo cp -R "${script_dir}/container/etc/." "${image_root}/etc/"
sudo chroot "${image_root}" systemctl enable systemd-networkd.service

sudo chroot "${image_root}" rm -f /etc/machine-id
sudo chroot "${image_root}" systemd-machine-id-setup

sudo chroot "${image_root}" useradd --create-home --user-group --groups wheel agent
sudo chroot "${image_root}" passwd --delete agent

sudo cp -R "${script_dir}/host/etc/." /etc/
sudo systemctl stop "systemd-nspawn@${image_name}.service" &> /dev/null

sudo machinectl remove "${image_name}" &> /dev/null
sudo mv "${image_root}" "/var/lib/machines/${image_name}"

sudo systemctl start "systemd-nspawn@${image_name}.service"
sudo machinectl shell agent@"${image_name}" /bin/dnf -y install "${packages[@]}"
