#!/bin/bash
set -eo pipefail

export NONINTERACTIVE=1

install_brew () {
	# https://docs.brew.sh/Homebrew-on-Linux
		
	sudo dnf -y group install development-tools
	sudo dnf -y install procps-ng curl file bubblewrap
		
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	echo >> "${HOME}/.bashrc"
	echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> "${HOME}/.bashrc"
	eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
}

if ! command -v brew > /dev/null 2>&1; then
	install_brew
fi

brew doctor
