#!/bin/bash
set -eo pipefail

script_dir=$(cd -- "$(dirname -- "${0}")" && pwd)
bridge_name="bridge-0"

sudo install -m 644 "${script_dir}/host/${bridge_name}.netdev" /etc/systemd/network/
sudo install -m 644 "${script_dir}/host/${bridge_name}.network" /etc/systemd/network/
sudo systemctl enable --now systemd-networkd
sudo networkctl reload
