#!/bin/bash
set -eo pipefail

if ! command -v brew >/dev/null 2>&1; then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	echo >> "${HOME}/.bashrc"
	echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> "${HOME}/.bashrc"
	eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi
