#!/bin/bash
set -eo pipefail

os_root=$1
os_ver=$2

sudo dnf -y \
	--installroot="$os_root" \
	--releasever="$os_ver" \
	--use-host-config \
	install systemd systemd-networkd systemd-resolved \
	dbus-broker coreutils bash fedora-release util-linux

sudo systemd-firstboot --root="$os_root" --delete-root-password --force
sudo systemctl --root "$os_root" enable systemd-networkd systemd-resolved
