[Distribution]
Distribution=fedora
Release=44

[Output]
Format=directory
OutputDirectory=/var/lib/machines
Output=sandbox

[Content]
Packages=
	fedora-release
	bash
	dnf
	sudo
	systemd
	systemd-networkd
	util-linux
WithRecommends=yes
RootPassword=hashed:
MachineId=random
Bootable=no
