#!/bin/bash
set -eo pipefail

script_dir="$HOME/github.com/mattkellymt/techstack/fedora"
bridge_name="bridge-0"
image_name="fedora"
os_root="/var/lib/machines/${image_name}"
os_ver="44"

bridge_netdev=$(cat << EOF
[NetDev]
Name=${bridge_name}
Kind=bridge
EOF
)

bridge_network=$(cat << EOF
[Match]
Name=${bridge_name}

[Network]
Address=10.0.0.1/24
DHCPServer=yes
IPMasquerade=ipv4
ConfigureWithoutCarrier=yes
EOF
)

image_nspawn=$(cat << EOF
[Exec]
NotifyReady=yes

[Network]
Bridge=${bridge_name}
EOF
)

# dnf
sudo dnf upgrade -y --refresh
sudo dnf install -y systemd systemd-container systemd-resolved

# write + install the container bridge config (10.0.0.1/24, DHCP server + NAT)
sudo install -m 644 /dev/stdin /etc/systemd/network/${bridge_name}.netdev  <<< "$bridge_netdev"
sudo install -m 644 /dev/stdin /etc/systemd/network/${bridge_name}.network <<< "$bridge_network"
sudo install -m 644 /dev/stdin /etc/systemd/nspawn/${image_name}.nspawn <<< "$image_nspawn"

# ensure container networking + DNS are enabled and running (idempotent)
sudo systemctl enable --now systemd-networkd
sudo systemctl enable --now systemd-resolved
sudo networkctl reload

# remove the existing container
sudo systemctl stop "systemd-nspawn@${image_name}.service"
sudo machinectl remove "$image_name" 2>/dev/null || true

# create a fedora container
sudo dnf -y \
	--installroot="$os_root" \
	--releasever="$os_ver" \
	--use-host-config \
	install fedora-release sudo bash dnf \
	systemd systemd-networkd systemd-resolved

sudo systemd-firstboot --root="$os_root" --delete-root-password --force
sudo systemctl --root "$os_root" enable systemd-networkd systemd-resolved
sudo systemctl start "systemd-nspawn@${image_name}.service"
