#!/bin/bash
set -eo pipefail

script_dir=$(cd -- "$(dirname -- "${0}")" && pwd)
host_config="${script_dir}/host"

# dnf
sudo dnf -y upgrade
sudo dnf -y install systemd systemd-networkd systemd-container

# bridge
sudo install -m 644 \
	"${host_config}/bridge-0.netdev" \
	"${host_config}/bridge-0.network" \
	/etc/systemd/network/
sudo systemctl enable --now systemd-networkd
sudo networkctl reload

# image
"${script_dir}/build_image"
