#!/bin/bash
set -eo pipefail

script_dir="${HOME}/github.com/mattkellymt/techstack/fedora"
distribution="fedora"
release="44"
bridge_name="bridge-0"
bridge_address="10.203.17.1/24"
image_name="${distribution}-${release}"
machine_dir="/var/lib/machines"
os_root="${machine_dir}/${image_name}"

bridge_netdev=$(cat << EOF
[NetDev]
Name=${bridge_name}
Kind=bridge
EOF
)

bridge_network=$(cat << EOF
[Match]
Name=${bridge_name}

[Network]
Address=${bridge_address}
DHCPServer=yes
IPMasquerade=ipv4
ConfigureWithoutCarrier=yes
EOF
)

image_nspawn=$(cat << EOF
[Exec]
NotifyReady=yes

[Network]
Bridge=${bridge_name}
EOF
)

mkosi_config=$(cat << EOF
[Distribution]
Distribution=${distribution}
Release=${release}

[Output]
Format=directory
OutputDirectory=${machine_dir}
Output=${image_name}

[Content]
Packages=
	fedora-release
	sudo
	bash
	dnf
	systemd
	systemd-networkd
	systemd-resolved
	mkosi
WithRecommends=yes
RootPassword=hashed:
MachineId=random
Bootable=no
EOF
)

# materialize config files
for ext in {netdev,network,conf,nspawn}; do
	rm -f "${script_dir}"/*."${ext}"
done

install -m 644 /dev/stdin "${script_dir}/${bridge_name}.netdev" <<< "${bridge_netdev}"
install -m 644 /dev/stdin "${script_dir}/${bridge_name}.network" <<< "${bridge_network}"
install -m 644 /dev/stdin "${script_dir}/${image_name}.nspawn" <<< "${image_nspawn}"
install -m 644 /dev/stdin "${script_dir}/${image_name}.mkosi.conf" <<< "${mkosi_config}"

# dnf
sudo dnf upgrade -y --refresh
sudo dnf install -y systemd systemd-container systemd-resolved mkosi

# install the container bridge config
sudo install -m 644 "${script_dir}/${bridge_name}.netdev" "/etc/systemd/network/${bridge_name}.netdev"
sudo install -m 644 "${script_dir}/${bridge_name}.network" "/etc/systemd/network/${bridge_name}.network"
sudo install -m 644 "${script_dir}/${image_name}.nspawn" "/etc/systemd/nspawn/${image_name}.nspawn"

# ensure container networking + DNS are enabled and running (idempotent)
sudo systemctl enable --now systemd-networkd
sudo systemctl enable --now systemd-resolved
sudo networkctl reload

# remove the existing container
sudo systemctl stop "systemd-nspawn@${image_name}.service"
sudo machinectl remove "${image_name}" 2>/dev/null || true

# create a container
sudo mkosi --directory "${script_dir}" --include "${script_dir}/${image_name}.mkosi.conf" --force build

sudo systemctl --root "${os_root}" enable systemd-networkd systemd-resolved
sudo systemctl start "systemd-nspawn@${image_name}.service"
