#!/bin/bash
set -euo pipefail 

# fedora 44
sudo dnf upgrade -y

# repo
cd ~/github.com/mattkellymt/techstack
git fetch origin main
current_branch=$(git branch --show-current)

if [ "$current_branch" = "main" ]; then
    git reset --hard origin/main
    git clean -fd
fi

# uv
cd ~/github.com/mattkellymt/techstack
uv self update
uv tool upgrade --all
uv sync --upgrade

# ollama
url="https://api.github.com/repos/ollama/ollama/releases/latest"
latest=$(curl -fsSL "$url" | jq -r .tag_name | sed 's/v//')
current=$(ollama --version | sed 's/ollama version is //')

if [ "$latest" != "$current" ]; then
	curl -fsSL https://ollama.com/install.sh | sh
fi

# opencode
opencode upgrade
