#!/bin/bash
set -eo pipefail

main() {
	# dnf
	sudo dnf upgrade -y --refresh

	# brew
	brew update
	brew upgrade -y

	# github
	cd "$HOME/github.com/mattkellymt/techstack"
	git fetch origin main
	current_branch=$(git branch --show-current)

	if [ "$current_branch" = "main" ]; then
		git reset --hard origin/main
		git clean -fd
	fi
}
main
