[Distribution]
Distribution=${distribution}
Release=${release}

[Output]
Format=directory
OutputDirectory=${machine_dir}
Output=${image_name}

[Content]
Packages=
	fedora-release
	bash
	dnf
	sudo
	util-linux
	systemd
	systemd-networkd
WithRecommends=yes
RootPassword=hashed:
MachineId=random
Bootable=no
